// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./.vitepress/comps/about.vue')['default']
    AboutUs: typeof import('./.vitepress/comps/about-us.vue')['default']
    AlbumRow: typeof import('./.vitepress/comps/album-row.vue')['default']
    Chromatone: typeof import('./.vitepress/comps/chromatone.vue')['default']
    Contact: typeof import('./.vitepress/comps/contact.vue')['default']
    ExpBlob: typeof import('./.vitepress/comps/exp/blob.vue')['default']
    ExpFleck: typeof import('./.vitepress/comps/exp/fleck.vue')['default']
    ExpSimplex: typeof import('./.vitepress/comps/exp/simplex.vue')['default']
    ExpVisuals: typeof import('./.vitepress/comps/exp/visuals.vue')['default']
    ExpWaves: typeof import('./.vitepress/comps/exp/waves.vue')['default']
    JamDeezerCircle: typeof import('~icons/jam/deezer-circle')['default']
    LaAmazon: typeof import('~icons/la/amazon')['default']
    LaApple: typeof import('~icons/la/apple')['default']
    LaBandcamp: typeof import('~icons/la/bandcamp')['default']
    LaGithub: typeof import('~icons/la/github')['default']
    LaInstagram: typeof import('~icons/la/instagram')['default']
    LaSpotify: typeof import('~icons/la/spotify')['default']
    LaVimeo: typeof import('~icons/la/vimeo')['default']
    LaVk: typeof import('~icons/la/vk')['default']
    LaYandex: typeof import('~icons/la/yandex')['default']
    LaYoutube: typeof import('~icons/la/youtube')['default']
    LinkButton: typeof import('./.vitepress/theme/components/link-button.vue')['default']
    Links: typeof import('./.vitepress/theme/components/links.vue')['default']
    TopHead: typeof import('./.vitepress/comps/top-head.vue')['default']
    UilBoombox: typeof import('~icons/uil/boombox')['default']
    VideoRow: typeof import('./.vitepress/comps/video-row.vue')['default']
    ZLogo: typeof import('./.vitepress/comps/z/logo.vue')['default']
  }
}

export { }
