/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./.vitepress/comps/about.vue')['default']
    AboutUs: typeof import('./.vitepress/comps/about-us.vue')['default']
    AlbumRow: typeof import('./.vitepress/comps/album-row.vue')['default']
    Chromatone: typeof import('./.vitepress/comps/chromatone.vue')['default']
    Contact: typeof import('./.vitepress/comps/contact.vue')['default']
    EventCard: typeof import('./.vitepress/comps/event-card.vue')['default']
    EventsList: typeof import('./.vitepress/comps/events-list.vue')['default']
    EventsRow: typeof import('./.vitepress/comps/events-row.vue')['default']
    ExpBlob: typeof import('./.vitepress/comps/exp/blob.vue')['default']
    ExpFleck: typeof import('./.vitepress/comps/exp/fleck.vue')['default']
    ExpVisuals: typeof import('./.vitepress/comps/exp/visuals.vue')['default']
    ExpWaves: typeof import('./.vitepress/comps/exp/waves.vue')['default']
    JamDeezerCircle: typeof import('~icons/jam/deezer-circle')['default']
    LaAmazon: typeof import('~icons/la/amazon')['default']
    LaApple: typeof import('~icons/la/apple')['default']
    LaBandcamp: typeof import('~icons/la/bandcamp')['default']
    LaExpand: typeof import('~icons/la/expand')['default']
    LaGithub: typeof import('~icons/la/github')['default']
    LaInstagram: typeof import('~icons/la/instagram')['default']
    LaPause: typeof import('~icons/la/pause')['default']
    LaPlay: typeof import('~icons/la/play')['default']
    LaSpotify: typeof import('~icons/la/spotify')['default']
    LaVimeo: typeof import('~icons/la/vimeo')['default']
    LaVk: typeof import('~icons/la/vk')['default']
    LaYandex: typeof import('~icons/la/yandex')['default']
    LaYoutube: typeof import('~icons/la/youtube')['default']
    LinkButton: typeof import('./.vitepress/theme/components/link-button.vue')['default']
    Links: typeof import('./.vitepress/theme/components/links.vue')['default']
    TopHead: typeof import('./.vitepress/comps/top-head.vue')['default']
    UilBoombox: typeof import('~icons/uil/boombox')['default']
    VideoRow: typeof import('./.vitepress/comps/video-row.vue')['default']
    YoutubeEmbed: typeof import('./.vitepress/comps/youtube-embed.vue')['default']
    ZLogo: typeof import('./.vitepress/comps/z/logo.vue')['default']
  }
}
