/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./.vitepress/theme/components/about.vue')['default']
    AboutUs: typeof import('./.vitepress/theme/components/about-us.vue')['default']
    AlbumRow: typeof import('./.vitepress/theme/components/album-row.vue')['default']
    Chromatone: typeof import('./.vitepress/theme/components/chromatone.vue')['default']
    Contact: typeof import('./.vitepress/theme/components/contact.vue')['default']
    EventList: typeof import('./.vitepress/theme/components/event/list.vue')['default']
    ExpBlob: typeof import('./.vitepress/theme/components/exp/blob.vue')['default']
    ExpFleck: typeof import('./.vitepress/theme/components/exp/fleck.vue')['default']
    ExpVisuals: typeof import('./.vitepress/theme/components/exp/visuals.vue')['default']
    ExpWaves: typeof import('./.vitepress/theme/components/exp/waves.vue')['default']
    JamDeezerCircle: typeof import('~icons/jam/deezer-circle')['default']
    LaAmazon: typeof import('~icons/la/amazon')['default']
    LaApple: typeof import('~icons/la/apple')['default']
    LaBandcamp: typeof import('~icons/la/bandcamp')['default']
    LaExpand: typeof import('~icons/la/expand')['default']
    LaGithub: typeof import('~icons/la/github')['default']
    LaInstagram: typeof import('~icons/la/instagram')['default']
    LaPause: typeof import('~icons/la/pause')['default']
    LaPlay: typeof import('~icons/la/play')['default']
    LaSpotify: typeof import('~icons/la/spotify')['default']
    LaVimeo: typeof import('~icons/la/vimeo')['default']
    LaVk: typeof import('~icons/la/vk')['default']
    LaYandex: typeof import('~icons/la/yandex')['default']
    LaYoutube: typeof import('~icons/la/youtube')['default']
    LinkButton: typeof import('./.vitepress/theme/components/link-button.vue')['default']
    Links: typeof import('./.vitepress/theme/components/links.vue')['default']
    Pages: typeof import('./.vitepress/theme/components/pages.vue')['default']
    TopHead: typeof import('./.vitepress/theme/components/top-head.vue')['default']
    UilBoombox: typeof import('~icons/uil/boombox')['default']
    VideoRow: typeof import('./.vitepress/theme/components/video-row.vue')['default']
    YoutubeEmbed: typeof import('./.vitepress/theme/components/youtube-embed.vue')['default']
    ZLogo: typeof import('./.vitepress/theme/components/z/logo.vue')['default']
  }
}
